# Generated by Django 3.2.13 on 2023-06-21 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_auto_20230621_0001'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='baseuser',
            managers=[
            ],
        ),
    ]
