# Generated by Django 3.2.13 on 2023-06-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_alter_baseuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
