# Generated by Django 3.2.13 on 2023-11-07 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_baseuser_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='cpf',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.cpf', verbose_name='cpf'),
        ),
    ]
