# Generated by Django 3.2.13 on 2023-06-21 00:42

from django.db import migrations, models
import order.models.products


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, unique=True)),
                ('category', models.CharField(choices=[('bebida', 'bebida'), ('lanche', 'lanche'), ('sobremesa', 'sobremesa'), ('acompanhamento', 'acompanhamento')], max_length=40, verbose_name='categoria')),
                ('description', models.CharField(max_length=400, unique=True)),
                ('size', models.CharField(choices=[('pequeno', 'pequeno'), ('medio', 'medio'), ('grande', 'grande')], max_length=10, verbose_name='tamanho')),
                ('image', models.FileField(blank=True, null=True, upload_to=order.models.products.imageFileUpdload, verbose_name='imagem')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
