# Generated by Django 3.2.13 on 2023-06-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_orderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('em aberto', 'em aberto'), ('fila', 'fila'), ('fazendo', 'fazendo'), ('disponivel', 'disponivel'), ('entregue', 'entregue'), ('cancelado', 'cancelado')], max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='changes',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='alteracoes'),
        ),
    ]
