# Generated by Django 3.2.13 on 2023-06-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20230622_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('em aberto', 'em aberto'), ('fila', 'fila'), ('fazendo', 'fazendo'), ('disponivel', 'disponivel'), ('entregue', 'entregue'), ('cancelado', 'cancelado')], default='em aberto', max_length=10, verbose_name='status'),
        ),
    ]
