# Generated by Django 3.2.13 on 2023-06-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
