# Generated by Django 3.2.13 on 2023-06-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_session_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('pequeno', 'pequeno'), ('medio', 'medio'), ('grande', 'grande')], max_length=10, null=True, verbose_name='tamanho'),
        ),
    ]
