# Generated by Django 3.2.13 on 2023-06-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=0, help_text='em centavos', verbose_name='valor'),
        ),
    ]
