# Generated by Django 3.2.13 on 2023-06-26 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_product_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=400),
        ),
    ]
