# Generated by Django 3.2.13 on 2023-06-30 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_cpf'),
        ('order', '0009_auto_20230627_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cpf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.cpf', verbose_name='cpf'),
        ),
    ]
